name: NPEC pipeline

on:
  # Runs on pushes targeting the default branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write-all

jobs:
  PoetrySetup:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install project
        run: |
          pip install coverage
          pip install pytest
          pip install sqlalchemy
          pip install pandas
          pip install geopandas
          pip install matplotlib
      - name: Run tests
        run: |
          coverage run -m pytest && coverage xml coverage.xml
      - name: Get Cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: ./coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}