name: Share Poetry Installation

on:
  push:
    branches:
      - main

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Poetry
        uses: actions/cache@v2
        with:
          path: ~/.poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Poetry
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Set up Poetry
        run: |
          echo "::add-path::$HOME/.poetry/bin"
          poetry --version

  use-poetry:
    needs: install-poetry
    runs-on: ubuntu-latest
    steps:
      - name: Restore Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
