name: Share Poetry Installation

on:
  push:
    branches:
      - main

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Poetry
        uses: actions/cache@v2
        with:
          path: ~/.poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Poetry
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Set up Poetry
        run: echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> $GITHUB_ENV && source $GITHUB_ENV && poetry --version

  download-packages:
    needs: install-poetry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies from pyproject.toml
        run: poetry install

  use-poetry:
    needs: download-packages
    runs-on: ubuntu-latest
    steps:
      - name: Restore Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      # Your steps here that use Poetry for dependency management or other tasks
